### ISSUE TITLE
update to 0.10.3 failing

### ISSUE THREAD

**Issue by sannykr** [conda-forge/ipdb-feedstock#6]
@vamega: Do you know why the build failed? It had passed all checks.

**Comment by vamega** [comment]
I do not.
I will take a look into what happened either later today or tomorrow.

Varun Madiath

**Comment by vamega** [comment]
Seems like it was unable to upload this to binstar.
I've done the naieve thing and restarted the CI jobs.

If that doesn't work I'll look into what caused it.
Perhaps we need to re-render the feedstock because the CI scripts have been updated?

**Comment by vamega** [comment]
Seems like restarting the jobs did not fix the issue.

I'll try to see if I can re-render the feedstocks tomorrow. If anyone can
do this before then and submit a pull request that would be incredible.

The ci failed on uploading to binstar. This explains why it passed in the
pull request but failed after the merge. Pull requests don't upload to
binstar after all.

**Comment by sannykr** [comment]
@vamega: I was trying to update one more package and faced similar problem. It passed all checks, but after merging with feedstock,  it failed. I was told to look at the following link: 
https://github.com/conda-forge/conda-forge.github.io/issues/426#issuecomment-321897876

**Comment by vamega** [comment]
I'm closing this since it's been so long, and I've managed a newer version of this feedstock.
